// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/out/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      // Auto-generated by `next build`; not meant to be edited or linted.
      '**/next-env.d.ts',
      // Agent worktrees are isolated checkouts, not part of this tree's lint scope.
      '**/.claude/**',
      // Zero-build MV3 browser extension (vanilla JS, browser/chrome globals);
      // linted via its own tooling, not this TypeScript-focused root config.
      'apps/extension/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
);
