// @ts-check
import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/out/**',
      '**/coverage/**',
      '**/*.tsbuildinfo',
      // Auto-generated by `next build`; not meant to be edited or linted.
      '**/next-env.d.ts',
      // Agent worktrees are isolated checkouts, not part of this tree's lint scope.
      '**/.claude/**',
      // Zero-build MV3 browser extension (vanilla JS, browser/chrome globals);
      // linted via its own tooling, not this TypeScript-focused root config.
      'apps/extension/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  // Service worker: runs in a ServiceWorkerGlobalScope, not a browser window.
  // Inlined subset of the `globals` package's `serviceworker` entry so we
  // don't need to add `globals` as a direct devDependency.
  {
    files: ['apps/web/public/sw.js'],
    languageOptions: {
      globals: {
        self: 'readonly',
        caches: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        clients: 'readonly',
        skipWaiting: 'readonly',
        addEventListener: 'readonly',
        console: 'readonly',
      },
    },
  },
  // Node.js scripts (icon generators, tooling helpers) use Node.js globals.
  {
    files: ['scripts/**'],
    languageOptions: {
      globals: {
        Buffer: 'readonly',
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
  },
);
